

var countries = {  
    "Albania": { description: "Closed to outsiders for much of the 20th century, Albania has long been Mediterranean Europe's enigma. Until fairly recently its rumpled mountains, fortress towns and sparkling beaches were merely a rumour on most travel maps.", cities: "Buenos Aires", name: "1N_xG_lIdVc5zj5e00tdYk0Wc6jb2VkrJ", place:"countries/Albania/albania.html",  },
    "Argentina": { description: "Argentina is a beautiful tropical country that is located in the southern Argentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pArgentina is a beautiful tropical country that is located in the southern pportion of South America. The official language of Argentina is Spanish, and most people there speak the Castilian Spanish dialect.", cities: "Buenos Aires", name: "1GS4qNC4F_8ih8tk-7syaJY4jCqjJSnJU", place: "countries/Argentina/argentina.html",  },
    "Australia": { description: "Australia, officially the Commonwealth of Australia,[11] is a sovereign country comprising the mainland of the Australian continent, the island of Tasmania and numerous smaller islands. It is the largest country in Oceania and the world's sixth-largest country by total area.", cities: "Buenos Aires", name: "1ChLgC0VOgiOJKPBxvo_oba48-TZzeIgA", place:"countries/Australia/australia.html",  },
    "Austria": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "13PzquCG0gLAksOyW3U9FCYwWeMPHoHqg", place:"countries/Austria/austria.html",  },
    "The Bahamas": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1N7kjQ9EYVcQ1_rxnKqKINZZQbs_0Prmt", place:"countries/Bahamas/bahamas.html",  },
    "Barbados": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1gqLfKeF536LYYb8-wgv7Cw42XpS5aBZM", place:"countries/Barbados/barbados.html",  },
    "Belgium": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1GfcPMoX5_oh1Vq38L3hrrPFsRi76ApS0", place:"countries/Belgium/belgium.html",  },
    "Bolivia": { description: "Argentina is a beautiArgentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1erXPz4RzndUjAH3e5xnyg44qIdLcIDNV", place:"countries/Bolivia/bolivia.html", },
    "Brazil": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1uB7Cd_bKwouQG-13_nSfU4vK2WL6kVyy", place:"countries/Brazil/brazil.html",  },
    "Brunei": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1I4DwsuOJ3zS9mV-k_dmapO6gQEB1NQV9", place:"countries/Brunei/brunei.html",  },
    "Bulgaria": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1kTLj6KCuU4TENiEjLhWwkC7-exHFHRqh", place:"countries/Bulgaria/bulgaria.html",  },
    "Cabo Verde": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "11ULBql3eAtZae_JuQeprgMKX1VSpIgTp", place:"countries/CaboVerde/cabo-verde.html",  },
    "Cameroon": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1X77_Ieu2cNapongZcyO9eqpNnBd6Wurt", place:"countries/Cameroon/cameroon.html",  },
    "Chad": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1eGRNiaMOlmsgZD_xbR6-2K7bSAjQhljU", place:"countries/Chad/chad.html",  },
    "Chile": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires",   name: "1VwhA8uzNLhi_D3WW8qyz5nPRXpLsK-NW", place:"countries/Chile/chile.html", },
    "China": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1Dg8Jkop8QLkjfHI0Ptcd5RR48mqdL5Ao", place:"countries/China/china.html",  },
    "Colombia": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires",  name: "1rkuwpKuO0fmLbeD_PzCr_JqmSU3ljNFo", place:"countries/Colombia/colombia.html", },
    "Costa Rica": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1A5hqSlfhIo8x6d7VdExCS_WQZGBo56g_", place:"countries/CostaRica/costa-rica.html",  },
    "Croatia": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires",  name: "1_1wlvEnssGYOup6RDG_ywVeLm0FnyIby", place:"countries/Croatia/croatia.html", },
    "Cuba": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires",  name: "1ftxzAUFqjwxZLyXvDjPb3BJF9dh7CM_m", place:"countries/Cuba/cuba.html", },
    "Cyprus": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1dAHX7Yw04i6C2AO-k_Wqqyd1fLdNFiuH", place:"countries/Cyprus/cyprus.html", },
    "Czech Republic": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires" , name: "1vS2l8WgI1NRCqSydplH_w6F7urh1_YIR", place:"countries/CzechRepublic/czech-republic.html", },
    "Denmark": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1wVB9W4EXDThiPTtmqUhEb1i474fCM270", place:"countries/Denmark/denmark.html",  },
    "Dominican Republic": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1Qc3aTbXRXHr3IVGhhgbKD5vjoPdqLMus", place:"countries/DominicanRepublic/dominicana-republic.html",},
    "Ecuador": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1WXAJT_xlMwfvYPbfnBcawwG02O0w9x9d", place:"countries/Ecuador/ecuador.html",    },
    "Egypt": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "17c1wu8579WduM2e37cx1wfKhGNPS2lkn", place:"countries/Egypt/egypt.html",  },
    "El Salvador": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "10U_Wc1_sXacbDSOlnpWFcpQFjyluQLVg", place:"countries/ElSalvado/el-salvador.html",  },
    "El Salvador": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1f84jkh2us0iCHLXTGSVFeOadmDCiXmc2", place:"countries/France/france.html",  },
    "Germany": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1D8hB-fkL8IGoTyqvdr_gIDsAt7hdZX7s", place:"countries/Germany/germany.html",  },
    "Greece": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1Wt1mbSABzf83XOL5M1l6KAsiwcZzw9S9", place:"countries/Greece/greece.html",  },
    "Haiti": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1GR5qFf-ysI1Q-A8c3vsYFjtGDYQTdZ0l", place:"countries/Haiti/haiti.html",  },
    "Hungary": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1M7bIAlqdQ7oUnDNCuLwxJtxQP3dDgQDi", place:"countries/Hungary/hungary.html",  },
    "Iceland": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1NP46ucav17F4PPCAGTymjbqylrLvACJd", place:"countries/Iceland/iceland.html",  },
    "India": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1uwVz1GaxnBvXavXK1lABHJ5cI8m7CTaT", place:"countries/India/india.html",  },
    "Indonesia": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "12o1u-dTzRYmkrKuSPr1MpYhCTdYlYY3q", place:"countries/Indonesia/indonesia.html",  },
    "Ireland": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1S4poEhLzTS6B0M0UTMU3qxn_SktrYlfK", place:"countries/Ireland/ireland.html",  },
    "Isreal": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1AF7gi2UXOt-BzTYvkn8AknCkZM1NmTUC", place:"countries/Isreal/isreal.html",  },
    "Italy": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1sSaTcWRCvJNCbx9zVD0ZnEswhzpQd5EQ", place:"countries/Italy/italy.html",  },
    "Japan": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1OD3gfe6IfmbCwVhJ8jOrSXxPWKsFe183", place:"countries/Japan/japan.html",  },
    "Luxembourg": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1ZIgj3oClRpWFcvgZdcWMW9jFfK6YdlFR", place:"countries/Luxembourg/luxembourg.html",  },
    "Malta": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1R4g-Ss6LnKwpRVvEXczAEboqp_1izVNN", place:"countries/Malta/malta.html",  },
    "Mexico": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1MO4tGHgO3jHvVS2Jtw4lp1SuGNzD67xK", place:"countries/Mexico/mexico.html",  },
    "Monaco": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1XXFL-FQaF8mvI49Cine3Jw1FOFW34w2c", place:"countries/Monaco/monaco.html",  },
    "Morocco": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "11VR79uz3hkmVIukM9aef5G6ERc84G3ZM", place:"countries/Morocco/morocco.html",  },
    "Netherlands": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1kocO4EKzZ-yPghgUHiMu5hoJS264uFFT", place:"countries/Netherlands/netherlands.html",  },
    "New Zealand": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1ecoH5NWOc8Bk0i_SEgG_3k-Wbghij0nr", place:"countries/NewZealand/new-zealand.html",  },
    "Norway": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1tMdmfZiHOEa9RaRn9-oxZzMyxNRKYXRf", place:"countries/Norway/norway.html",  },
    "Peru": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1cetwKjRCA4Mlm77-XYpmaQlQWy3clgCs", place:"countries/Peru/peru.html",  },
    "Portugal": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1Moejznkz1aCkXCUCIQanQEOOGs_GzZsw", place:"countries/Portugal/portugal.html",  },
    "Russia": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1Ts5CGfRPM1DLX1XxumQ9P5MGgMhFtawu", place:"countries/Russia/russia.html",  },
    "Spain": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1RAMMf2vENlDV3Qd1DZncfPzUbtPRiH4V", place:"countries/Spain/spain.html",  },
    "Sweden": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1rui3xnZMRhKjRpn34E3zBALJYysoGgzL", place:"countries/Sweden/sweden.html",  },
    "Switzerland": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "19nc8FwfNWu-Aip8txqVwpTgtTRhEFJ_T", place:"countries/Switzerland/switzerland.html",  },
    "Thailand": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1eLisAl3JkhoQQrpp5oFL8tHNUiA_azfx", place:"countries/Thailand/thailand.html",  },
    "United Arab Emirates": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1w8_jas6s-Nzoa8rN35X2q5Efxse9ut6Z", place:"countries/UAE/uae.html",  },
    "United Kingdom": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1QEEZGOxAFOC40A1WEgWKBxnYpzZwaSAR", place:"countries/UK/uk.html",  },
    "United States": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1kiWdnOtawmCuObfg0A7-NCYXaaNJAtj1", place:"countries/Uruguay/uruguay.html",  },
    "Uruguay": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "1PC09BJiYv7oPuhQG7EriAWNT8pGtyPSr", place:"countries/usa/usa.html",  },
    "Vatican City": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "17ESi0k7iKqfSTQjpVdcVgddiXhWGjqj6", place:"countries/VaticanCity/vatican-city.html",  },
    "Venezuela": { description: "Bulgaria. Argentina is a beautiful tropical country that is located in the southern portion of South America. The official language of Argentina is Spanish, and most people there speak the Castil", cities: "Buenos Aires", name: "17q4-z-spc_HEckXhpFvVEt_Yi1UWQdhJ", place:"countries/Venezuela/venezuela.html",  },
  }
  var wrapper = $('#wrapper'), container;
  for (var key in countries){
     
   
      container = $('<div id="countries" class="container"></div>');
      wrapper.append(container);
      container.append('<div class="country">' + key +'</div>');
      container.append('<div class="images">' + `<a href="https://drive.google.com/uc?export=view&id=${countries[key].name}"><img src="https://drive.google.com/uc?export=view&id=${countries[key].name}">` + '</a>'  + '</div>');
      container.append('<div class="description">' + '<h2 class="h2">' + 'Description' + '</h2>' + countries[key].description  +'</div>' );
      container.append('<div class="btn-position">' + `<a class="button" href="${countries[key].place}">` + 'Learn more' + '</a>' + '</div>');
  }



function myFunction() {
  var x = document.getElementById("name");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }

} 
var myArray = []; 

for(var key in countries) {
    myArray.push(key);
}


var wrap = $('#wrap'), middle;

function getRandomValue() {
  console.log(rand);

  var rand = myArray[Math.floor(Math.random() * myArray.length)];
middle = $('<div class="middle"></div>');
wrap.append(middle);
middle.append('<div id="name">' + rand +'</div>' + `<a class="button" href="${countries[key].place}">` + 'Learn more' + '</a>' + '</div>' );
console.log(rand);


}

